"""WebVoyager — CUA-Lite wrapper for the WebVoyager Selenium web benchmark.

Container-only SINGLETON: one shared ``cua-lite/webharbor.webvoyager`` container per env-server
owns Selenium/Chromium sessions and exposes a JSON RPC API
(``docker/server.py``). The host-side env is a thin client that imports no
Selenium/WebVoyager code; task metadata is read from the checked-in static
manifest ``data/tasks.json`` generated by ``scripts/utils/tasks.sh``.
"""

from __future__ import annotations

import asyncio
import base64
import dataclasses
import importlib.util
import json
import logging
import os
import re
import time
import urllib.error
import urllib.request
from functools import partial
from pathlib import Path
from typing import Any, ClassVar

from lite.core.metadata import LiteCUAMetadata
from lite.core.tools.action_space import LITE_DESKTOP_KEY_ACTION_NAMES
from lite.core.tools.calls import EnvAction, RuntimeEnvAction
from lite.core.tools.extra_tools import (
    LiteBrowserNavToolSet,
    LiteFinishToolSet,
)
from lite.core.tools.schemas import (
    BaseTools,
    make_tool_schema,
    schema_type_error_reason,
    tool_arguments_match_schema_route_keys,
    tool_schema_name,
    tool_schema_validation_errors,
)
from lite.gym.base import LiteBaseEnv
from lite.gym.errors import CapacityExhausted, EnvDepsMissingError
from lite.gym.registry import invalidate_services, register, registry
from lite.gym.remote.reaper import SingletonContainerServices
from lite.gym.services import register_services
from lite.gym.types import (
    EXECUTED_ACTIONS_INFO_KEY,
    LiteEnvObservation,
    LiteEnvStepResult,
)
from lite.gym.utils import config as env_config
from lite.gym.utils.backend.docker import docker_rm_f, docker_run
from lite.gym.utils.backend.freshness import image_for
from lite.gym.utils.backend.model_inputs import (
    coerce_model_duration,
    project_model_keys,
)
from lite.gym.utils.config import naming
from lite.gym.utils.feedback.errors import (
    MODEL_ACTION_ERROR_TYPES,
    ToolErrorFeedback,
    current_feedback,
    invalid_action_arguments_message,
    model_visible_error_detail,
    parse_container_action_error_record,
    record_model_action_error,
    tool_execution_error_message,
    unavailable_action_message,
)
from lite.gym.utils.feedback.ingress import (
    invalid_action_message,
    is_active_extra_tool_call,
    prepare_env_tool_calls,
    standalone_tool_call_feedback,
)
from lite.gym.utils.feedback.results import (
    build_tool_results_from_decisions,
    ordered_tool_call_ids,
)
from lite.gym.utils.feedback.surface import (
    copy_valid_actions,
    resolve_extra_tools,
    resolve_valid_actions,
)
from lite.utils.image import png_from_b64_async

logger = logging.getLogger(__name__)

ENV_DIR = str(Path(__file__).parent)
CFG = env_config.load(ENV_DIR)




# ---------------------------------------------------------------------------
# Config defaults
# ---------------------------------------------------------------------------
_MAX_STEPS = CFG.env_kwargs["max_steps"]
_STEP_TIMEOUT = CFG.env_kwargs["step_timeout"]
_POST_ACTION_DELAY = CFG.env_kwargs["post_action_delay"]
_VIEWPORT = tuple(CFG.env_kwargs["viewport"])
_FIX_BOX_COLOR = CFG.env_kwargs["fix_box_color"]
_USE_SOM = CFG.env_kwargs["use_som"]
_VALID_ACTIONS = resolve_valid_actions(
    CFG.env_kwargs["valid_actions"], env_name="webharbor.webvoyager", platform="browser",
)
_EXTRA_TOOLS = CFG.env_kwargs["extra_tools"]
_EVAL_CONFIG: dict[str, Any] = CFG.env_kwargs.get("eval_config") or {}

_RPC_PORT = CFG.server_kwargs["rpc_port"]
_RPC_URL = CFG.server_kwargs["rpc_url"] or f"http://localhost:{_RPC_PORT}"
_INSTANCES = CFG.server_kwargs["instances"]
_PAGE_LOAD_TIMEOUT_S = CFG.server_kwargs["page_load_timeout_s"]
_SCRIPT_TIMEOUT_S = CFG.server_kwargs["script_timeout_s"]
_RESET_SETTLE_S = CFG.server_kwargs["reset_settle_s"]
_INSTANCE_TTL_S = CFG.server_kwargs["instance_ttl_s"]
_REAPER_INTERVAL_S = CFG.server_kwargs["reaper_interval_s"]
_RM_TIMEOUT_S = float(os.environ.get("CUA_LITE_WEBHARBOR_WEBVOYAGER_RM_TIMEOUT_S", str(CFG.server_kwargs["rm_timeout_s"])))

_WEBHARBOR_WEBVOYAGER_IMAGE = "cua-lite/webharbor.webvoyager:latest"
_WEBHARBOR_WEBVOYAGER_PORT_START = 7800
_WEBHARBOR_WEBVOYAGER_PORT_END = 7899
# Shared CUA-Lite browser-nav tools resolvable via the shared schema source
# (``LiteBrowserNavToolSet``). click_elem/fill are NOT here: they are not part of the
# shared LiteBrowserNavToolSet set (would resolve to an empty schema), and the
# SoM index-clicking interface is the WebHarbor click/input tools below — so
# advertising them would be a silent footgun. Requesting them now raises a clear
# "not wired" error at the config boundary instead.
#
# This is a SELECTION, not an order: ``get_tool_schemas(include=)`` emits in
# ``LiteBrowserNavToolSet`` declaration order, so the pair is advertised
# ``goto, back``.
_WEBHARBOR_WEBVOYAGER_BROWSER_NAV: tuple[str, ...] = ("back", "goto")
_WEB_TEXT_COORD_RE = re.compile(r"\s*@\s*\(\d+\s*,\s*\d+\)")


def _function_tool_schema(
    name: str,
    description: str,
    properties: dict[str, dict[str, Any]],
    required: list[str],
) -> dict[str, Any]:
    return make_tool_schema(
        name,
        description=description,
        parameters={
            "type": "object",
            "properties": properties,
            "required": required,
        },
    )


_WEBHARBOR_LOCAL_TOOL_SCHEMAS: dict[str, dict[str, Any]] = {
    "click": _function_tool_schema(
        "click",
        "Click the interactive element at index [N] in the DOM tree.",
        {
            "index": {
                "type": "integer",
                "description": "The [N] index of the element shown in the DOM tree and screenshot marks.",
            },
        },
        ["index"],
    ),
    "input": _function_tool_schema(
        "input",
        "Type text into the interactive input element at index [N].",
        {
            "index": {
                "type": "integer",
                "description": "The [N] index of the input element shown in the DOM tree and screenshot marks.",
            },
            "text": {"type": "string", "description": "The text to enter."},
        },
        ["index", "text"],
    ),
    "scroll": _function_tool_schema(
        "scroll",
        "Scroll the page by a number of viewport pages.",
        {
            "down": {"type": "boolean", "description": "True to scroll down, false to scroll up."},
            "pages": {
                "type": "number",
                "description": "Number of viewport pages to scroll, e.g. 0.5, 1, or 2.",
            },
        },
        ["down", "pages"],
    ),
    "navigate": _function_tool_schema(
        "navigate",
        "Navigate the browser directly to a URL.",
        {"url": {"type": "string", "description": "The URL to navigate to."}},
        ["url"],
    ),
    "go_back": _function_tool_schema(
        "go_back",
        "Navigate to the previous page in browser history.",
        {},
        [],
    ),
}
_WEBHARBOR_LOCAL_TOOL_NAMES = frozenset(_WEBHARBOR_LOCAL_TOOL_SCHEMAS)


class WebVoyagerTools(BaseTools):
    """What webharbor.webvoyager declares: two shared nav tools + five local ones.

    The CUA-Lite nav bodies come from the shared ``LiteBrowserNavToolSet`` source;
    the WebHarbor-style tools are local to this env because their names and
    parameter shapes are benchmark-specific aliases over the Selenium RPC
    server's actions. ``response``/``terminate`` are resolved centrally and must
    NOT be listed.
    """

    _SCHEMAS: ClassVar[dict[str, dict[str, Any]]] = {
        **{
            tool_schema_name(schema): schema
            for schema in LiteBrowserNavToolSet.get_tool_schemas(
                include=list(_WEBHARBOR_WEBVOYAGER_BROWSER_NAV)
            )
        },
        **_WEBHARBOR_LOCAL_TOOL_SCHEMAS,
    }


_WEBHARBOR_STANDALONE_EXTRA_TOOLS = (
    frozenset({"back", "goto", "input", "navigate", "go_back"})
    | LiteFinishToolSet.get_tool_names()
)
_WEBHARBOR_WEBVOYAGER_SHAPE_ROUTED_EXTRA_TOOLS = frozenset({"click", "scroll"})
#: Finish tools cannot live in an env's own set, so the union is not optional.
_KNOWN_STANDALONE_TOOL_NAMES = WebVoyagerTools.get_tool_names() | LiteFinishToolSet.get_tool_names()


def _is_standalone_extra_call(action: EnvAction) -> bool:
    name = action["name"]
    args = action["arguments"]
    if name in _WEBHARBOR_STANDALONE_EXTRA_TOOLS:
        return True
    return (name == "click" and "index" in args) or (name == "scroll" and "pages" in args)


def _shape_routed_extra_argument_error(
    action: EnvAction,
    extra_tool_schemas: list[dict[str, Any]] | None,
) -> str | None:
    """Validate same-name SoM extras before they reach the RPC server.

    ``click``/``scroll`` can mean either coordinate GUI actions or SoM DOM-index
    extras. Once the model includes the SoM discriminator key, the call belongs
    to the extra-tool schema and malformed parameters must not fall through to
    coordinate execution or become container-dependent feedback.
    """
    name = action["name"]
    if name not in _WEBHARBOR_WEBVOYAGER_SHAPE_ROUTED_EXTRA_TOOLS:
        return None
    if not _is_standalone_extra_call(action):
        return None
    schema = next(
        (schema for schema in extra_tool_schemas or [] if tool_schema_name(schema) == name),
        None,
    )
    if schema is None:
        return None
    args = action["arguments"]
    if not tool_arguments_match_schema_route_keys(schema, args):
        return invalid_action_arguments_message(
            name,
            f"{name}.arguments do not match its tool schema",
        )

    errors = tool_schema_validation_errors(schema, args)
    if not errors:
        return None
    err = errors[0]
    path = ".".join(str(part) for part in err.path)
    field = f"{name}.arguments.{path}" if path else f"{name}.arguments"
    if err.validator == "type" and isinstance(err.validator_value, str):
        return invalid_action_arguments_message(
            name,
            schema_type_error_reason(field, err.validator_value),
        )
    if err.validator == "required":
        missing = str(err.message).split("'", 2)[1:2]
        if missing:
            return invalid_action_arguments_message(
                name,
                f"{name}.arguments.{missing[0]} is required",
            )
    return invalid_action_arguments_message(name, f"{field} {err.message}")


#: Builder-side no-override default, resolved ONCE at import.
_DEFAULT_EXTRA_TOOL_SCHEMAS = resolve_extra_tools(
    _EXTRA_TOOLS, tools=WebVoyagerTools, env_name="webharbor.webvoyager",
)


def _pair_webvoyager_action_errors(
    actions: list[EnvAction],
    result_call_ids: list[str | None],
    action_errors: list[dict[str, Any]] | None,
    legacy_errors: list[str],
) -> dict[str, str]:
    """Attribute container model-action errors to the originating call."""
    paired: dict[str, str] = {}

    def add(index: int, message: str) -> None:
        if index < 0 or index >= len(result_call_ids):
            return
        call_id = result_call_ids[index]
        if not call_id:
            return
        paired[call_id] = (
            f"{paired[call_id]}\n{message}" if call_id in paired else message
        )

    paired_indices: set[int] = set()
    structured_legacy_counts: dict[str, int] = {}

    def invalid_arguments_text(index: int, text: str, *, name: str | None = None) -> str:
        action_name = str(
            name or (actions[index]["name"] if 0 <= index < len(actions) else "action")
        )
        raw_detail = str(text).removeprefix(f"{action_name}: ").strip()
        detail = model_visible_error_detail(
            raw_detail,
            fallback="arguments could not be interpreted",
        )
        return invalid_action_arguments_message(action_name, detail)

    for raw_record in action_errors or []:
        fallback_name = None
        if isinstance(raw_record, dict):
            raw_index = raw_record.get("index")
            if isinstance(raw_index, int) and 0 <= raw_index < len(actions):
                fallback_name = str(actions[raw_index].get("name") or "action")
        record = parse_container_action_error_record(
            raw_record,
            result_call_ids=result_call_ids,
            fallback_name=fallback_name,
        )
        if record is None:
            continue
        index = record.index
        name = record.name
        error = record.error or record.message
        if record.kind == "model_action":
            add(index, invalid_arguments_text(index, error, name=name))
            legacy_text = f"{name}: {error}"
            structured_legacy_counts[legacy_text] = structured_legacy_counts.get(legacy_text, 0) + 1
        else:
            add(index, tool_execution_error_message(name, "execution failed"))
        paired_indices.add(index)

    next_index = 0
    for error in legacy_errors:
        text = str(error)
        if structured_legacy_counts.get(text, 0) > 0:
            structured_legacy_counts[text] -= 1
            continue
        index = next(
            (
                i for i in range(next_index, len(actions))
                if i not in paired_indices and text.startswith(f"{actions[i]['name']}:")
            ),
            None,
        )
        if index is None:
            index = next(
                (i for i in range(len(actions) - 1, -1, -1) if i not in paired_indices),
                None,
            )  # unmatched → best effort, never dropped while any call remains
            if index is None:
                continue
        else:
            next_index = index + 1
        add(index, invalid_arguments_text(index, text))
        paired_indices.add(index)
    return paired


def _strip_web_text_coords(text: str) -> str:
    """Remove visual center coordinates that Qwen may confuse with [N] ids."""
    return _WEB_TEXT_COORD_RE.sub("", text)


def _web_observation_text(resp: dict[str, Any], *, strip_coords: bool) -> str:
    web_text = str(resp.get("web_text") or "")
    if strip_coords:
        web_text = _strip_web_text_coords(web_text)

    parts: list[str] = []
    url = str(resp.get("url") or "")
    title = str(resp.get("title") or "")
    if url:
        parts.append(f"CURRENT URL: {url}")
    if title:
        parts.append(f"PAGE TITLE: {title}")
    if web_text:
        parts.append(f"DOM:\n{web_text}")
    return "\n".join(parts)


def _web_rejection_feedback_text(resp: dict[str, Any], web_text: str) -> str:
    if web_text:
        return web_text
    parts: list[str] = []
    url = str(resp.get("url") or "")
    title = str(resp.get("title") or "")
    if url:
        parts.append(f"CURRENT URL: {url}")
    if title:
        parts.append(f"PAGE TITLE: {title}")
    return "\n".join(parts) or "Current page context is unchanged."


_services_started: set[str] = set()


# ---------------------------------------------------------------------------
# VLM judge — prompts (original WebVoyager auto_eval.py, enhanced)
# ---------------------------------------------------------------------------
_JUDGE_SYSTEM_PROMPT = """\
As an evaluator, you will be presented with three primary components to assist in your role:

1. Web Task Instruction: A clear and specific directive in natural language detailing the online activity to carry out (e.g. conducting searches, verifying information, comparing prices, checking availability).

2. Result Screenshots: A visual representation of the screen showing the result or intermediate state of performing the web task. Serves as visual proof of the actions taken.

3. Result Response: A textual response obtained after the execution of the web task. Serves as the textual result.

-- You DO NOT NEED to interact with web pages or perform any actions yourself.
-- You SHOULD NOT make assumptions based on information not presented in the screenshot.
-- Your primary responsibility is to assess the web task instruction against the outcome depicted in the screenshots and in the response, evaluating whether the actions taken align with the given instructions.
-- NOTE that the instruction may involve more than one task. Failing to complete any part should be considered unsuccessful.
-- NOTE that the screenshot is authentic, but the response provided by the agent is generated at the end of web browsing, and there may be discrepancies between text and screenshots.
-- If the Result Response contradicts the screenshot, the screenshot content prevails. If the Result Response mentions content not visible in the screenshot, choose to believe the response.

A Reference Answer is provided for guidance. For 'possible' type tasks, other equally valid answers are also acceptable. For 'golden' type tasks, the reference is the expected answer.

You should elaborate on how you arrived at your final evaluation and then provide a definitive verdict on whether the task has been successfully accomplished, either as 'SUCCESS' or 'NOT SUCCESS'.\
"""

_JUDGE_USER_TMPL = """\
TASK: {instruction}

Reference Answer ({reference_type}): {reference_answer}{reference_notice}

Result Response: {answer}

{num} screenshot(s) at the end of the episode:\
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _derive_instances() -> int:
    if _INSTANCES:
        return int(_INSTANCES)
    try:
        from lite.gym.utils.server.capacity import cached_host_capacity
        host = cached_host_capacity()
        return max(2, min(int((host.ram_total_gb * 0.25) / 0.8), 32))
    except Exception as e:
        logger.warning("webharbor.webvoyager: capacity probe failed (%s); instances fallback to 8", type(e).__name__)
        return 8


_RESOLVED_INSTANCES = _derive_instances()


def _container_name(server_port: int | None = None) -> str:
    """``webharbor.webvoyager-<server_port>`` (or ``webharbor.webvoyager-d<pid>`` in direct mode).

    Thin wrapper over the canonical shared-singleton helper so reaper scope can
    never drift from webgym/mobilegym (D5)."""
    return naming.container_name("webharbor.webvoyager", server_port)


def _healthz(url: str) -> bool:
    if not url:
        return False
    try:
        with urllib.request.urlopen(url.rstrip("/") + "/healthz", timeout=3) as r:
            data = json.loads(r.read())
        return bool(data.get("ok"))
    except (urllib.error.URLError, OSError, ValueError):
        return False


# ---------------------------------------------------------------------------
# Task registration
# ---------------------------------------------------------------------------
def _load_tasks_json() -> dict[str, dict[str, Any]]:
    tasks_path = Path(__file__).parent / "data" / "tasks.json"
    if not tasks_path.is_file():
        raise FileNotFoundError(
            f"{tasks_path} not found. Re-generate with:\n"
            f"  bash lite/gym/envs/webharbor/webvoyager/scripts/utils/tasks.sh"
        )
    with tasks_path.open(encoding="utf-8") as f:
        return json.load(f)


def _task_others(meta: dict[str, Any], *, max_steps: int | None = None) -> dict[str, Any]:
    # dict() is shallow — sever list values (e.g. the on-disk ``sites``) so a
    # consumer mutating registered/live others can't corrupt the other side.
    others: dict[str, Any] = {k: list(v) if isinstance(v, list) else v
                              for k, v in (meta.get("others") or {}).items()}
    defaults = {
        "source": meta.get("source", "webharbor.webvoyager"),
        "upstream_id": meta.get("upstream_id", ""),
        "web_name": meta.get("web_name", ""),
        "site_slug": meta.get("site_slug", ""),
        "sites": [meta["site_slug"]] if meta.get("site_slug") else [],
        "start_url": meta.get("start_url", ""),
        "upstream_url": meta.get("upstream_url", ""),
        "max_steps": max_steps,
    }
    for key, value in defaults.items():
        if value not in (None, "", []):
            others.setdefault(key, value)
    for key in ("reference_answer", "reference_type", "reference_notice", "level", "gaia_task_id"):
        if key in meta and meta[key] is not None:
            others[key] = meta[key]
    return others


def _task_metadata(meta: dict[str, Any]) -> LiteCUAMetadata:
    """Same-source metadata builder. valid_actions
    and extra_tool_schemas carry the yaml defaults; others carries the
    task-determined fields incl. the DEFAULT max_steps and viewport (yaml
    fact) — the live env amends them on env_kwargs override."""
    base_max_steps = int(meta.get("max_steps") or 15)
    others = _task_others(meta, max_steps=base_max_steps)
    # viewport's DEFAULT is a yaml fact → it belongs in the registered copy
    # too (the invariant: registered == no-override live); the live env
    # overwrites it only when env_kwargs override.
    others["viewport"] = tuple(_VIEWPORT)
    return LiteCUAMetadata(
        dims=("browser", "use"),
        valid_actions=copy_valid_actions(_VALID_ACTIONS),
        extra_tool_schemas=list(_DEFAULT_EXTRA_TOOL_SCHEMAS),
        others=others,
    )


def _register_tasks() -> None:
    # Env-wide make() defaults from default.yaml make_kwargs.
    registry.set_env_make_kwargs("webharbor.webvoyager", CFG.make_kwargs)
    for task_id, meta in _load_tasks_json().items():
        base_max_steps = int(meta.get("max_steps") or 15)
        split = str(meta.get("split") or "eval")

        register(
            key=f"webharbor.webvoyager@{task_id}",
            entry_point=partial(_make_remote_env, task_id=task_id, task=meta, base_max_steps=base_max_steps),
            split=split,
            metadata=_task_metadata(meta),
            max_steps=base_max_steps,
            step_timeout=_STEP_TIMEOUT,
        )
    logger.debug("Registered webharbor.webvoyager tasks from static manifest")


# ---------------------------------------------------------------------------
# Thin JSON RPC client env
# ---------------------------------------------------------------------------
class RemoteWebVoyagerEnv(LiteBaseEnv):
    EXTRA_TOOLS: ClassVar[type[BaseTools]] = WebVoyagerTools

    def __init__(
        self,
        *,
        task_id: str,
        task: dict[str, Any],
        base_max_steps: int,
        max_steps: int | None = _MAX_STEPS,
        post_action_delay: float = _POST_ACTION_DELAY,
        viewport: tuple[int, int] = _VIEWPORT,
        fix_box_color: bool = _FIX_BOX_COLOR,
        use_som: bool = _USE_SOM,
        valid_actions: list[str] | None = _VALID_ACTIONS,
        extra_tools: list[str] | None = _EXTRA_TOOLS,
        eval_config: dict[str, Any] | None = None,
        skip_eval: bool = False,
        cursor: bool = True,
        **_: Any,
    ) -> None:
        self._task_id = task_id
        # dict(...): `task` is the shared registration-side row — copy,
        # don't alias.
        self._task = dict(task)
        self._base_max_steps = base_max_steps
        self._max_steps = max_steps
        self._post_action_delay = post_action_delay
        self._cursor = cursor
        self._viewport = tuple(viewport)
        self._fix_box_color = fix_box_color
        self._use_som = use_som
        self._rpc_url = os.environ.get("WEBHARBOR_WEBVOYAGER_RPC_URL") or _RPC_URL
        self._instance_id: str | None = None
        # Unconditional assignment: the signature default (yaml-sourced) is
        # the single source of truth for "omitted", so an EXPLICIT
        # ``valid_actions: null`` keeps its shared meaning (no filtering).
        self._valid_actions = resolve_valid_actions(
            valid_actions, env_name="webharbor.webvoyager", platform="browser",
        )
        self._eval_config: dict[str, Any] = {**_EVAL_CONFIG, **(eval_config or {})}
        self._skip_eval = skip_eval

        requested = list(extra_tools or [])
        # Resolve + validate via the same helper the builder default uses
        # (registered == no-override live by construction).
        self._extra_tool_schemas = type(self).extra_tool_schemas(extra_tools)
        # ``== []`` not ``not ...``: only a DELIBERATE empty GUI enum (the
        # bid-only som rows) means "no coordinates"; ``None`` is the full GUI
        # surface and must keep its coordinates.
        self._strip_web_text_coords = (
            self._valid_actions == []
            and bool(set(requested) & _WEBHARBOR_LOCAL_TOOL_NAMES)
        )

        # Episode-level state for evaluation
        self._screenshots: list[bytes] = []
        self._agent_response: str | None = None
        self._last_observation_image: bytes | None = None
        self._last_observation_text: str | None = None
        self._last_observation_metadata: dict[str, Any] = {}
        self._step_count = 0

    @property
    def max_steps(self) -> int:
        return int(self._max_steps if self._max_steps is not None else self._base_max_steps)

    # Shared with registration (module-level builder); exposed on the class
    # per the family-wide convention.
    _task_metadata = staticmethod(_task_metadata)

    def _runtime_metadata(self) -> LiteCUAMetadata:
        # env_kwargs amendments: valid_actions / extra_tools overrides,
        # max_steps override, viewport (env_kwarg with a yaml default).
        md = self._task_metadata(self._task)
        return dataclasses.replace(
            md,
            valid_actions=self._valid_actions,
            extra_tool_schemas=self._extra_tool_schemas,
            others={**md.others, "max_steps": self.max_steps,
                    "viewport": self._viewport},
        )

    # -----------------------------------------------------------------------
    # Evaluation helpers
    # -----------------------------------------------------------------------

    def _require_eval_deps(self) -> None:
        """Fail fast at reset() if the VLM judge can't run.

        Pass ``skip_eval=True`` to run without evaluation.
        """
        if importlib.util.find_spec("openai") is None:
            raise EnvDepsMissingError(
                what="openai package not importable (needed for VLM judge)",
                install="pip install openai",
                see="lite/gym/envs/webharbor/webvoyager/README.md",
            )
        api_key_var = self._eval_config.get("api_key_env_var", "OPENAI_API_KEY")
        if not os.environ.get(api_key_var):
            raise EnvDepsMissingError(
                what=f"WebVoyager VLM judge needs {api_key_var} (set OPENAI_BASE_URL for a proxy)",
                install=f"export {api_key_var}=...   # or pass skip_eval=True to run without evaluation",
                see="lite/gym/envs/webharbor/webvoyager/README.md",
            )

    def _build_eval_config(self) -> dict[str, Any]:
        """Resolve final eval config: yaml defaults → per-run overlay → env vars."""
        cfg = dict(self._eval_config)
        cfg.setdefault("model", "gpt-4.1")
        cfg.setdefault("max_attached_imgs", 3)
        cfg.setdefault("api_key_env_var", "OPENAI_API_KEY")
        if os.environ.get("WEBHARBOR_WEBVOYAGER_EVAL_MODEL"):
            cfg["model"] = os.environ["WEBHARBOR_WEBVOYAGER_EVAL_MODEL"]
        base_url = os.environ.get("WEBHARBOR_WEBVOYAGER_EVAL_BASE_URL") or os.environ.get("OPENAI_BASE_URL")
        if base_url:
            cfg["base_url"] = base_url
        if os.environ.get("WEBHARBOR_WEBVOYAGER_EVAL_API_KEY_VAR"):
            cfg["api_key_env_var"] = os.environ["WEBHARBOR_WEBVOYAGER_EVAL_API_KEY_VAR"]
        return cfg

    async def _evaluate(self) -> tuple[float | None, dict[str, Any]]:
        """Evaluate the episode at its end (terminated or truncated).

        Returns (reward, eval_info). Reward is None when evaluation is skipped
        or the agent gave no answer; 0.0 or 1.0 when the judge ran.

        Judge runtime errors propagate so the rollout can retry (they must NOT
        be silently scored 0.0 — that would corrupt collected data).
        """
        if self._skip_eval:
            return None, {}

        if not self._agent_response:
            return None, {
                "agent_response": None,
                "eval_skipped": True,
                "eval_skip_reason": "no_agent_response",
            }

        return await asyncio.to_thread(self._vlm_evaluate_sync)

    def _vlm_evaluate_sync(self) -> tuple[float, dict[str, Any]]:
        """Synchronous GPT-4V judge call (runs in a thread via asyncio.to_thread).

        Follows the original WebVoyager auto_eval.py evaluation protocol:
        shows the task instruction, agent response, and the last N screenshots
        to a VLM and parses SUCCESS / NOT SUCCESS from the verdict.
        """
        import openai

        cfg = self._build_eval_config()
        model = cfg["model"]
        max_imgs = int(cfg.get("max_attached_imgs", 3))
        api_key_var = cfg["api_key_env_var"]
        api_key = os.environ.get(api_key_var, "")
        base_url = cfg.get("base_url")

        client = openai.OpenAI(api_key=api_key, base_url=base_url or None)

        # Build reference context
        ref_answer = self._task.get("reference_answer", "") or ""
        ref_type = self._task.get("reference_type", "possible") or "possible"
        ref_notice = self._task.get("reference_notice", "") or ""
        if ref_notice:
            ref_notice = f"\n(Note: {ref_notice.strip()})"

        user_text = _JUDGE_USER_TMPL.format(
            instruction=self._task.get("instruction", ""),
            reference_answer=ref_answer,
            reference_type=ref_type,
            reference_notice=ref_notice,
            answer=self._agent_response,
            num=min(max_imgs, len(self._screenshots)),
        )

        # Attach last max_imgs screenshots as base64 inline images
        image_parts: list[dict[str, Any]] = []
        for png_bytes in self._screenshots[-max_imgs:]:
            b64 = base64.b64encode(png_bytes).decode("ascii")
            image_parts.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/png;base64,{b64}", "detail": "low"},
            })

        messages: list[dict[str, Any]] = [
            {"role": "system", "content": _JUDGE_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": [{"type": "text", "text": user_text}] + image_parts + [
                    {"type": "text", "text": "Your verdict:\n"},
                ],
            },
        ]

        logger.info(
            "webharbor.webvoyager judge: task=%s model=%s imgs=%d answer=%r",
            self._task_id, model, len(image_parts), (self._agent_response or "")[:80],
        )

        for attempt in range(5):
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=messages,
                    max_tokens=1000,
                    temperature=0,
                    seed=42,
                )
                break
            except Exception as e:
                if attempt < 4 and ("429" in str(e) or "rate" in str(e).lower() or "RateLimitError" in type(e).__name__):
                    wait = 10 * (2 ** attempt)
                    logger.warning("webharbor.webvoyager judge rate-limited (attempt %d/5), retrying in %ds: %s", attempt + 1, wait, e)
                    time.sleep(wait)
                else:
                    raise
        verdict = response.choices[0].message.content or ""
        logger.info("webharbor.webvoyager judge verdict: %s", verdict[:300])

        if "NOT SUCCESS" in verdict:
            reward = 0.0
        elif "SUCCESS" in verdict:
            reward = 1.0
        else:
            # Malformed response — treat as failure but log for debugging
            logger.warning("webharbor.webvoyager judge returned no SUCCESS/NOT SUCCESS verdict: %r", verdict[:200])
            reward = 0.0

        return reward, {
            "agent_response": self._agent_response,
            "eval_model": model,
            "eval_verdict": verdict,
            "reward": reward,
        }

    # -----------------------------------------------------------------------
    # RPC transport
    # -----------------------------------------------------------------------

    def _post(self, path: str, body: dict[str, Any]) -> dict[str, Any]:
        url = self._rpc_url.rstrip("/") + path
        data = json.dumps(body).encode()
        req = urllib.request.Request(url, data=data, method="POST", headers={"Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", errors="replace")
            if e.code == 503:
                raise CapacityExhausted(
                    what=f"webharbor.webvoyager container pool full ({path}): {detail}",
                    retry_after_s=60.0,
                ) from e
            raise RuntimeError(f"webharbor.webvoyager container {path} returned {e.code}: {detail}") from e

    # -----------------------------------------------------------------------
    # Gym interface
    # -----------------------------------------------------------------------

    async def reset(self) -> LiteEnvObservation:
        if not self._skip_eval:
            self._require_eval_deps()
        if self._instance_id is not None:
            await self.close()

        self._screenshots = []
        self._agent_response = None

        resp = await asyncio.to_thread(
            self._post,
            "/reset",
            {
                "task_id": self._task_id,
                "upstream_id": self._task.get("upstream_id", ""),
                "instruction": self._task.get("instruction", ""),
                "start_url": self._task.get("start_url", "https://www.google.com/"),
                "site_slug": self._task.get("site_slug", ""),
                "max_steps": self.max_steps,
                "viewport": list(self._viewport),
                "fix_box_color": self._fix_box_color,
                "use_som": self._use_som,
                "cursor": self._cursor,
            },
        )
        self._instance_id = resp["instance_id"]
        self._step_count = 0

        # Decode the screenshot ONCE (off-loop) and share it between the evaluation
        # buffer and the observation — avoids a second, synchronous multi-MB
        # b64decode of the same payload on the event loop.
        png = await png_from_b64_async(resp.get("screenshot_b64"))
        if png:
            self._screenshots.append(png)
        web_text = _web_observation_text(resp, strip_coords=self._strip_web_text_coords)
        metadata = {
            "url": resp.get("url", ""),
            "title": resp.get("title", ""),
            "web_text": web_text,
        }
        self._last_observation_image = png
        self._last_observation_text = _web_rejection_feedback_text(resp, web_text)
        self._last_observation_metadata = {
            "url": resp.get("url", ""),
            "title": resp.get("title", ""),
            "downloads": [],
        }

        return LiteEnvObservation(
            image=png,
            text=resp.get("instruction") or self._task.get("instruction", ""),
            metadata=metadata,
        )

    async def step(self, actions: list[RuntimeEnvAction]) -> LiteEnvStepResult:
        if self._instance_id is None:
            raise RuntimeError("webharbor.webvoyager step() called before reset()")
        input_actions = actions
        result_call_ids = ordered_tool_call_ids(input_actions)
        metadata = self.metadata
        actions_with_result_ids, action_errors = prepare_env_tool_calls(
            actions,
            metadata,
            defer_extra_schema_validation_for=_WEBHARBOR_WEBVOYAGER_SHAPE_ROUTED_EXTRA_TOOLS,
        )
        action_errors: dict[str, ToolErrorFeedback] = dict(action_errors)
        actions_to_send: list[EnvAction] = []
        sent_result_call_ids: list[str | None] = []
        extra_tool_schemas = metadata.extra_tool_schemas
        for action, result_call_id in actions_with_result_ids:
            name = action["name"]
            if name == "done":
                if result_call_id:
                    action_errors[result_call_id] = current_feedback(
                        unavailable_action_message(name)
                    )
                continue
            argument_error = _shape_routed_extra_argument_error(
                action,
                extra_tool_schemas,
            )
            if argument_error:
                if result_call_id:
                    action_errors[result_call_id] = current_feedback(argument_error)
                continue
            tool_feedback = standalone_tool_call_feedback(
                action,
                _KNOWN_STANDALONE_TOOL_NAMES,
                extra_tool_schemas,
                is_standalone_action_tool=_is_standalone_extra_call,
            )
            if tool_feedback is not None:
                if result_call_id:
                    action_errors[result_call_id] = tool_feedback
                continue
            if _is_standalone_extra_call(action):
                if not is_active_extra_tool_call(action, extra_tool_schemas):
                    if result_call_id:
                        action_errors[result_call_id] = current_feedback(
                            unavailable_action_message(name)
                        )
                    continue
            else:
                invalid_action = invalid_action_message(action, metadata.valid_actions)
                if invalid_action:
                    if result_call_id:
                        action_errors[result_call_id] = current_feedback(invalid_action)
                    continue
            if name == "wait":
                try:
                    duration = coerce_model_duration(
                        action["arguments"].get("duration", 1.0),
                        action_name="wait",
                    )
                except MODEL_ACTION_ERROR_TYPES as e:
                    record_model_action_error(
                        action_errors,
                        result_call_id,
                        e,
                        action_name=name,
                    )
                    continue
                action = {
                    **action,
                    "arguments": {**action["arguments"], "duration": duration},
                }
            if name in LITE_DESKTOP_KEY_ACTION_NAMES:
                try:
                    # This container drives SELENIUM (ActionChains + `Keys.*`), not
                    # Playwright — project to the W3C WebDriver code points the
                    # container's `_selenium_key` passes straight through. An
                    # unprojected token would be TYPED AS LITERAL TEXT there.
                    # ``keys`` is REQUIRED and must be non-empty: the container's
                    # `if keys:` presses nothing for an empty list, so accepting
                    # one returned a normal post-action screenshot for a keypress
                    # that never happened -- the model could not tell. A missing
                    # or empty list is a malformed argument, reported through the
                    # same ``record_model_action_error`` channel as a bad
                    # ``wait.duration`` or an unknown key token.
                    keys = project_model_keys(
                        action["arguments"].get("keys", []),
                        action_name=name,
                        backend="selenium",
                    )
                except MODEL_ACTION_ERROR_TYPES as e:
                    record_model_action_error(
                        action_errors,
                        result_call_id,
                        e,
                        action_name=name,
                    )
                    continue
                action = {
                    **action,
                    "arguments": {**action["arguments"], "keys": keys},
                }
            actions_to_send.append(action)
            sent_result_call_ids.append(result_call_id)

        # Budget is consumed by the TURN, not by whether anything was
        # executable -- a step whose calls were all rejected still cost the
        # model a turn. Incrementing after the early return let a model that
        # only ever emits invalid calls run forever (sibling
        # ``online_mind2web/main.py`` increments before the same branch).
        self._step_count += 1
        if not actions_to_send:
            # Skipping the RPC is correct -- there is nothing to execute -- but
            # the step that EXHAUSTS the budget still has to be scored. Without
            # this the episode ended ``truncated=True, reward=None`` and a
            # complete trajectory was silently thrown away. ``_evaluate`` is
            # host-side here (the container always returns ``reward: None``), so
            # the fast path can score without a round-trip. Mirrors the sibling
            # ``online_mind2web/main.py``.
            truncated = self._step_count >= self.max_steps
            reward: float | None = None
            eval_info: dict[str, Any] = {}
            if truncated:
                reward, eval_info = await self._evaluate()
            return build_tool_results_from_decisions(
                LiteEnvStepResult(
                    reward=reward,
                    terminated=False,
                    truncated=truncated,
                    info={
                        EXECUTED_ACTIONS_INFO_KEY: [],
                        "errors": [],
                        "downloads": self._last_observation_metadata.get("downloads", []),
                        "answer": self._agent_response,
                        **eval_info,
                    },
                ),
                ordered_call_ids=result_call_ids,
                continue_call_ids=result_call_ids,
                images=[self._last_observation_image],
                text=self._last_observation_text,
                metadata=self._last_observation_metadata,
                feedback=action_errors,
            )

        resp = await asyncio.to_thread(
            self._post,
            "/step",
            {
                "instance_id": self._instance_id,
                "actions": actions_to_send,
                "post_action_delay": self._post_action_delay,
                "cursor": self._cursor,
                # The host owns the budget: it is the side that sees the turns
                # whose calls were all rejected (the fast path above never reaches
                # the container). The container derives both its ``truncated`` flag
                # and the model-facing ``[Turn n/max]`` banner from this value.
                "step_count": self._step_count,
            },
        )

        terminated = bool(resp.get("terminated"))
        # Model-emitted calls that ENDED the episode. They get no continuation
        # observation: devs/migration/verify.py forbids a tool result for a
        # terminal call. Keyed on ``action["call_id"]`` and NOT on
        # ``result_call_id``, because an INTERNAL finish call has no ``call_id``
        # and the loop-detect wrapper's injected ``terminate`` carries the
        # intercepted NON-finish model call's id as ``_result_call_id`` -- that
        # call must still be answered. Gated on ``terminated`` because the
        # CONTAINER owns the verdict here: a finish call it did not honour leaves
        # a non-terminal step, whose calls all still need their result.
        terminal_call_ids = {
            action["call_id"]
            for action in actions_to_send
            if action["name"] in LiteFinishToolSet.get_tool_names() and action.get("call_id")
        } if terminated else set()
        truncated = bool(resp.get("truncated"))

        # Decode ONCE (off-loop); share between the eval buffer and the observation.
        # One result frame per EXECUTED action, in action order: the container
        # runs the whole batch, so it is the only side that can see the page
        # between two actions. ``screenshots_b64`` is the single owner of
        # this step's frames; ``/step`` returns no singular spelling.
        frames_b64 = resp["screenshots_b64"]
        pngs = [
            frame for frame in
            [await png_from_b64_async(entry) for entry in frames_b64]
            if frame is not None
        ]
        # R3: a GUI slot the host rejected owes a frame too, but it never
        # reaches the container so none comes back for it. Derive WHERE those
        # slots sat from the sent list -- no filter arm has to remember -- and
        # re-interleave. The host cannot capture mid-batch (the container runs
        # the whole batch in one RPC), so a rejected slot repeats the frame of
        # the action before it; that slot changed nothing, so the repeat is the
        # honest record.
        if pngs and len(actions_to_send) < len(actions_with_result_ids):
            sent_ids = [id(a) for a in actions_to_send]
            rebuilt: list[bytes] = []
            executed_frames = iter(pngs)
            for action, _rid in actions_with_result_ids:
                if id(action) in sent_ids:
                    rebuilt.append(next(executed_frames, pngs[-1]))
                else:
                    rebuilt.append(rebuilt[-1] if rebuilt else pngs[0])
            pngs = rebuilt
        png = pngs[-1] if pngs else None
        # The eval buffer is a TURN log, not a frame log: WebJudge scores the
        # observation the model was left with, so only the last frame joins it.
        if png:
            self._screenshots.append(png)

        # Capture agent answer (set by the container on a response() action)
        if resp.get("answer"):
            self._agent_response = resp["answer"]

        # Evaluate at episode end
        reward: float | None = resp.get("reward")
        eval_info: dict[str, Any] = {}
        if terminated or truncated:
            reward, eval_info = await self._evaluate()

        web_text = _web_observation_text(resp, strip_coords=self._strip_web_text_coords)
        obs_metadata = {
            "url": resp.get("url", ""),
            "title": resp.get("title", ""),
            "downloads": resp.get("downloads", []),
        }
        self._last_observation_image = png
        self._last_observation_text = _web_rejection_feedback_text(resp, web_text)
        self._last_observation_metadata = obs_metadata
        # Action failures are PER-CALL feedback, not page context: splicing them
        # into the shared web_text blob sent them to every call of the turn, so
        # the agent could not tell WHICH call failed. Pair them to the
        # originating call_id instead.
        container_action_errors = _pair_webvoyager_action_errors(
            actions_to_send,
            sent_result_call_ids,
            list(resp.get("action_errors") or []),
            list(resp.get("errors") or []),
        )
        action_errors.update({
            call_id: current_feedback(message)
            for call_id, message in container_action_errors.items()
        })
        return build_tool_results_from_decisions(
            LiteEnvStepResult(
                reward=reward,
                terminated=terminated,
                truncated=truncated,
                info={
                    EXECUTED_ACTIONS_INFO_KEY: resp.get("executed", []),
                    "errors": resp.get("errors", []),
                    "downloads": resp.get("downloads", []),
                    "answer": resp.get("answer"),
                    **eval_info,
                },
            ),
            ordered_call_ids=result_call_ids,
            continue_call_ids=[
                call_id for call_id in result_call_ids
                if call_id not in terminal_call_ids
            ],
            images=pngs,
            text=_web_rejection_feedback_text(resp, web_text),
            metadata=obs_metadata,
            feedback=action_errors,
        )

    async def close(self) -> None:
        self._last_observation_image = None
        self._last_observation_text = None
        self._last_observation_metadata = {}
        self._step_count = 0
        if self._instance_id is None:
            return
        iid = self._instance_id
        self._instance_id = None
        try:
            await asyncio.to_thread(self._post, "/close", {"instance_id": iid})
        except Exception as e:
            logger.warning("webharbor.webvoyager container close failed: %s", e)


class WebVoyagerContainerServices(SingletonContainerServices):
    rm_timeout_s = _RM_TIMEOUT_S
    rm_label = "webharbor.webvoyager"

    def container_name(self, scope) -> str:
        return _container_name(scope.server_port)

    def ensure(self, env_id: str) -> None:
        if env_id in _services_started:
            return
        url = os.environ.get("WEBHARBOR_WEBVOYAGER_RPC_URL", "")
        if _healthz(url):
            _services_started.add(env_id)
            return

        name = _container_name()
        docker_rm_f(name, timeout=_RM_TIMEOUT_S, label="webharbor.webvoyager")

        from lite.gym.utils.backend.ports import allocate_ports

        host_port = allocate_ports(n=1, range_start=_WEBHARBOR_WEBVOYAGER_PORT_START, range_end=_WEBHARBOR_WEBVOYAGER_PORT_END + 1)[0]
        vw, vh = _VIEWPORT
        mem = f"{max(4, _RESOLVED_INSTANCES * 8 // 10)}g"
        logger.info(
            "webharbor.webvoyager container: docker run %s (instances=%d, host_port=%d, mem=%s, viewport=%dx%d)",
            name, _RESOLVED_INSTANCES, host_port, mem, vw, vh,
        )
        docker_run(
            name,
            image_for("webharbor.webvoyager", tag=_WEBHARBOR_WEBVOYAGER_IMAGE),
            mem=mem,
            port=(host_port, 8000),
            env={
                "WEBHARBOR_WEBVOYAGER_INSTANCES": str(_RESOLVED_INSTANCES),
                "WEBHARBOR_WEBVOYAGER_VIEWPORT_W": str(vw),
                "WEBHARBOR_WEBVOYAGER_VIEWPORT_H": str(vh),
                "WEBHARBOR_WEBVOYAGER_PAGE_LOAD_TIMEOUT_S": str(_PAGE_LOAD_TIMEOUT_S),
                "WEBHARBOR_WEBVOYAGER_SCRIPT_TIMEOUT_S": str(_SCRIPT_TIMEOUT_S),
                "WEBHARBOR_WEBVOYAGER_RESET_SETTLE_S": str(_RESET_SETTLE_S),
                "WEBHARBOR_WEBVOYAGER_INSTANCE_TTL_S": str(_INSTANCE_TTL_S),
                "WEBHARBOR_WEBVOYAGER_REAPER_INTERVAL_S": str(_REAPER_INTERVAL_S),
            },
        )

        new_url = f"http://localhost:{host_port}"
        os.environ["WEBHARBOR_WEBVOYAGER_RPC_URL"] = new_url
        deadline = time.monotonic() + 180
        while time.monotonic() < deadline:
            if _healthz(new_url):
                _services_started.add(env_id)
                logger.info("webharbor.webvoyager container ready: %s", new_url)
                return
            time.sleep(2)
        raise EnvDepsMissingError(
            what=(
                "webharbor.webvoyager container started but /healthz was not "
                "ready within 180s"
            ),
            install=(
                "check the server logs and "
                "lite/gym/envs/webharbor/webvoyager/scripts/install.sh"
            ),
            see="lite/gym/envs/webharbor/webvoyager/README.md",
        )

    def health(self, _env_id: str) -> None:
        if not _healthz(os.environ.get("WEBHARBOR_WEBVOYAGER_RPC_URL", "")):
            raise EnvDepsMissingError(
                what="webharbor.webvoyager container not serving (/healthz unreachable)",
                install=(
                    "uv run --no-sync bash "
                    "lite/gym/envs/webharbor/webvoyager/scripts/install.sh"
                ),
                see="lite/gym/envs/webharbor/webvoyager/README.md",
            )

    def _evict_cache(self, env_id: str) -> None:
        _services_started.discard(env_id)
        os.environ.pop("WEBHARBOR_WEBVOYAGER_RPC_URL", None)
        invalidate_services(env_id)

    def reap(self, env_id: str, scope, in_use: set[str], *, boot: bool = False) -> int:
        try:
            return super().reap(env_id, scope, in_use, boot=boot)
        finally:
            if boot:
                self._evict_cache(env_id)

    def shutdown(self, env_id: str, scope) -> None:
        try:
            super().shutdown(env_id, scope)
        finally:
            self._evict_cache(env_id)

    # live_ids inherited from SingletonContainerServices: SINGLETON backends have
    # no per-instance reconcile view.


def _make_remote_env(*, task_id: str, task: dict[str, Any], base_max_steps: int, **kwargs: Any) -> RemoteWebVoyagerEnv:
    return RemoteWebVoyagerEnv(task_id=task_id, task=task, base_max_steps=base_max_steps, **kwargs)


_register_tasks()
register_services("webharbor.webvoyager", WebVoyagerContainerServices())
from lite.gym.services import BackendFamily, register_family  # noqa: E402

register_family("webharbor.webvoyager", BackendFamily.SINGLETON)
